import { Poppins } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { ModalProvider } from "../context/ModalProvider";
import { SideSheetProvider } from "../context/SideSheetProvider";
import { ThemeProvider } from "./dashboard/providers/ThemeProvider";

const font = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata = {
  title: "ProcSpy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <script src="https://kit.fontawesome.com/fc6a744dc7.js" crossorigin="anonymous"></script>
      </Head>
      <body className={`${font.variable} ${font.className} antialiased`}>
        <ThemeProvider>
          <SideSheetProvider>
            <ModalProvider>
              {children}
            </ModalProvider>
          </SideSheetProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}